version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/api
    schedule:
      interval: weekly
    groups:
      api-go:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      web-npm:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
